In [2]:
import numpy as np

In [3]:
a = [[1, 2], [3, 4]]

np.array([a, a, a])

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [4]:
letters = list(map(chr, range(ord('e'), ord('x')+1)))
random_string = "".join([np.random.choice(letters) for _ in range(462)])
print(len(random_string))
print(random_string)

462
fumujgjpwhrefkitminmwnuiswjkgugjnevgpqfevgpsfperevespxqffglvepnskurnmugkqoigkxlueeerlhvgnkukrrkurvsintusnmrxquiieougknkspmtiunqqomookipnrvlhpuokejwsgpxqmoxqjhjxksiemvwuolntqqongvqxvokqkxjwhilpesfqiuexwlhrtwwqqgknopjsqteggpnflwshoxregomnsisorgupvniikrunuptetujtrniqwrkqwqgsrifxuxreqqivnmqsvxkxemqmjlqeqjiwsirgmsffotpmieigjpvonekrnifjtemsfgusipvinxtpsgrglvqqnrongulfkwnjxlxrwelnvoulmvnlhgipixtffifxwmteikqgnoxjkequuthpntlrxoeimrshmikqjjrlurmjujuflnijkgfufsjloejfmi


In [5]:
# swap the keys and values in the dictionary below
nested_dictionary = {'GBR':{'e':'a', 'f':'b', 'g':'c', 'h': 'd'},
                     'PEL':{'i':'a', 'j':'b', 'k':'c', 'l': 'd'},
                     'ESN':{'m':'a', 'n':'b', 'o':'c', 'p': 'd'},
                     'BEB':{'q':'a', 'r':'b', 's':'c', 't': 'd'},
                     'CHE':{'u':'a', 'v':'b', 'w':'c', 'x': 'd'}}

#ginfo={'1|0':'a','1|1':'b','0|1':'c','0|0':'d'}
ginfo = {'a':'1|0', 'b':'1|1', 'c':'0|1', 'd':'0|0'}

dic = {'e':'GBR', 'f':'GBR', 'g':'GBR', 'h':'GBR',
       'i':'PEL', 'j':'PEL', 'k':'PEL', 'l':'PEL',
       'm':'ESN', 'n':'ESN', 'o':'ESN', 'p':'ESN',
       'q':'BEB', 'r':'BEB', 's':'BEB', 't':'BEB',
       'u':'CHE', 'v':'CHE', 'w':'CHE', 'x':'CHE'}

p = {} # should be filled like {1:GBR, 2:GBR, 3:PLE, 4:CHE, 5:CHE} 
        # the 1,2,3 etc .. would be positions in the String

for i, j in enumerate(random_string):
        p[i+1] = dic[j]

In [6]:
print(p)

{1: 'GBR', 2: 'CHE', 3: 'ESN', 4: 'CHE', 5: 'PEL', 6: 'GBR', 7: 'PEL', 8: 'ESN', 9: 'CHE', 10: 'GBR', 11: 'BEB', 12: 'GBR', 13: 'GBR', 14: 'PEL', 15: 'PEL', 16: 'BEB', 17: 'ESN', 18: 'PEL', 19: 'ESN', 20: 'ESN', 21: 'CHE', 22: 'ESN', 23: 'CHE', 24: 'PEL', 25: 'BEB', 26: 'CHE', 27: 'PEL', 28: 'PEL', 29: 'GBR', 30: 'CHE', 31: 'GBR', 32: 'PEL', 33: 'ESN', 34: 'GBR', 35: 'CHE', 36: 'GBR', 37: 'ESN', 38: 'BEB', 39: 'GBR', 40: 'GBR', 41: 'CHE', 42: 'GBR', 43: 'ESN', 44: 'BEB', 45: 'GBR', 46: 'ESN', 47: 'GBR', 48: 'BEB', 49: 'GBR', 50: 'CHE', 51: 'GBR', 52: 'BEB', 53: 'ESN', 54: 'CHE', 55: 'BEB', 56: 'GBR', 57: 'GBR', 58: 'GBR', 59: 'PEL', 60: 'CHE', 61: 'GBR', 62: 'ESN', 63: 'ESN', 64: 'BEB', 65: 'PEL', 66: 'CHE', 67: 'BEB', 68: 'ESN', 69: 'ESN', 70: 'CHE', 71: 'GBR', 72: 'PEL', 73: 'BEB', 74: 'ESN', 75: 'PEL', 76: 'GBR', 77: 'PEL', 78: 'CHE', 79: 'PEL', 80: 'CHE', 81: 'GBR', 82: 'GBR', 83: 'GBR', 84: 'BEB', 85: 'PEL', 86: 'GBR', 87: 'CHE', 88: 'GBR', 89: 'ESN', 90: 'PEL', 91: 'CHE', 92: 'PE

In [7]:
# swap the keys and values in the dictionary below
nested_dictionary = {'GBR':{'e':'a', 'f':'b', 'g':'c', 'h': 'd'},
                     'PEL':{'i':'a', 'j':'b', 'k':'c', 'l': 'd'},
                     'ESN':{'m':'a', 'n':'b', 'o':'c', 'p': 'd'},
                     'BEB':{'q':'a', 'r':'b', 's':'c', 't': 'd'},
                     'CHE':{'u':'a', 'v':'b', 'w':'c', 'x': 'd'}}

#ginfo={'1|0':'a','1|1':'b','0|1':'c','0|0':'d'}
ginfo = {'a':'1|0', 'b':'1|1', 'c':'0|1', 'd':'0|0'}

dic = {'e':'GBR', 'f':'GBR', 'g':'GBR', 'h':'GBR',
       'i':'PEL', 'j':'PEL', 'k':'PEL', 'l':'PEL',
       'm':'ESN', 'n':'ESN', 'o':'ESN', 'p':'ESN',
       'q':'BEB', 'r':'BEB', 's':'BEB', 't':'BEB',
       'u':'CHE', 'v':'CHE', 'w':'CHE', 'x':'CHE'}

genotypes = {}
N = len(random_string)

# initialize haplotype dictionary with 462 zeros for each sample
haplotypes = {'BEB':[0]*N, 'CHE':[0]*N, 'ESN':[0]*N, 'GBR':[0]*N, 'PEL':[0]*N}

for i, c in enumerate(random_string):
    # take sample as key and 0|1 etc as value
    genotypes.setdefault(dic[c], []).append(ginfo[nested_dictionary[dic[c]][c]])
    # set 1 in which position sample present
    haplotypes[dic[c]][i] = 1

In [8]:
# sort dictionary alphabetically
genotypes = dict(sorted(genotypes.items(), key = lambda x:x[0].lower()))
print(genotypes)

{'BEB': ['1|1', '0|0', '0|1', '1|0', '0|1', '1|1', '0|1', '1|0', '0|1', '1|1', '1|0', '1|1', '1|1', '1|1', '1|1', '0|1', '0|0', '0|1', '1|1', '1|0', '0|1', '0|0', '1|0', '1|0', '1|1', '0|1', '1|0', '1|0', '0|1', '0|0', '1|0', '1|0', '1|0', '1|0', '0|1', '1|0', '1|1', '0|0', '1|0', '1|0', '0|1', '1|0', '0|0', '0|1', '1|1', '0|1', '0|1', '1|1', '1|1', '0|0', '0|0', '0|0', '1|1', '1|0', '1|1', '1|0', '1|0', '0|1', '1|1', '1|1', '1|0', '1|0', '1|0', '0|1', '1|0', '1|0', '1|0', '0|1', '1|1', '0|1', '0|0', '1|1', '0|0', '0|1', '0|1', '0|0', '0|1', '1|1', '1|0', '1|0', '1|1', '1|1', '0|0', '0|0', '1|0', '1|0', '0|0', '0|0', '1|1', '1|1', '0|1', '1|0', '1|1', '1|1', '0|1'], 'CHE': ['1|0', '1|0', '0|1', '0|1', '1|0', '0|1', '1|0', '1|1', '1|1', '1|1', '0|0', '1|1', '1|0', '1|0', '0|0', '1|0', '1|1', '1|0', '1|0', '1|1', '1|0', '0|0', '1|0', '1|0', '1|0', '1|1', '1|0', '0|1', '0|0', '0|0', '0|0', '1|1', '0|1', '1|0', '1|1', '0|0', '1|1', '0|0', '0|1', '1|0', '0|0', '0|1', '0|1', '0|1', '0|1', '0

In [10]:
# split each 0|1 etc by | and make a list,,,thus apply on each sample
genotype_array = [[list(map(int, v.split('|'))) for v in val] for val in genotypes.values()]
print(genotype_array)

[[[0, 1], [0, 0], [0, 1], [1, 1], [1, 1], [1, 0], [0, 1], [1, 1], [1, 1], [1, 1], [1, 0], [1, 0], [1, 1], [1, 0], [1, 0], [1, 1], [1, 1], [0, 0], [0, 1], [1, 0], [0, 1], [0, 1], [1, 0], [0, 1], [0, 1], [0, 0], [1, 0], [1, 0], [0, 1], [0, 0], [0, 0], [0, 1], [1, 1], [1, 0], [0, 1], [1, 0], [1, 0], [1, 1], [1, 0], [1, 1], [0, 0], [1, 0], [0, 1], [1, 0], [1, 1], [0, 1], [0, 1], [0, 0], [1, 0], [0, 1], [1, 1], [1, 0], [0, 0], [0, 0], [1, 0], [1, 1], [0, 0], [0, 1], [0, 1], [1, 1], [0, 0], [0, 1], [1, 1], [0, 0], [0, 0], [1, 1], [1, 0], [1, 1], [0, 0], [0, 0], [0, 0], [0, 1], [0, 1], [0, 0], [0, 0], [1, 0], [1, 1], [0, 0], [0, 1], [0, 1], [0, 0], [1, 0], [0, 1], [0, 1], [0, 1], [0, 0], [0, 0], [1, 1], [0, 0], [1, 1], [0, 1], [0, 0], [0, 0]], [[1, 1], [1, 0], [0, 0], [1, 1], [1, 0], [1, 1], [0, 1], [1, 0], [0, 1], [0, 1], [1, 0], [0, 0], [0, 1], [0, 0], [0, 1], [1, 0], [1, 1], [0, 0], [0, 0], [0, 0], [1, 1], [0, 1], [0, 0], [0, 0], [1, 1], [0, 1], [1, 0], [0, 0], [1, 1], [1, 1], [1, 1], [0, 

In [9]:
gbr = [list(map(int, v.split('|'))) for v in genotypes['GBR']]
print(gbr)

[[1, 1], [0, 1], [0, 0], [1, 0], [1, 1], [0, 1], [0, 1], [1, 0], [0, 1], [1, 1], [1, 0], [0, 1], [1, 1], [1, 0], [1, 0], [1, 0], [1, 1], [1, 1], [0, 1], [1, 0], [0, 1], [0, 1], [1, 0], [1, 0], [1, 0], [0, 0], [0, 1], [1, 0], [0, 1], [0, 0], [1, 0], [0, 1], [0, 0], [1, 0], [0, 1], [0, 0], [1, 0], [1, 1], [1, 0], [0, 0], [0, 1], [1, 0], [0, 1], [0, 1], [1, 1], [0, 0], [1, 0], [0, 1], [0, 1], [1, 0], [0, 1], [1, 1], [1, 0], [1, 0], [1, 0], [0, 1], [1, 1], [1, 1], [1, 0], [0, 1], [1, 0], [1, 1], [1, 0], [1, 1], [0, 1], [0, 1], [0, 1], [0, 1], [1, 1], [1, 0], [0, 0], [0, 1], [1, 1], [1, 1], [1, 1], [1, 0], [0, 1], [1, 0], [0, 0], [1, 0], [0, 0], [1, 1], [0, 1], [1, 1], [1, 1], [1, 0], [1, 1]]


In [10]:
print(haplotypes)

{'BEB': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0

In [11]:
haplotype_array = [val for val in haplotypes.values()]
print(haplotype_array)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,

In [12]:
import pandas as pd

In [14]:
encoded = pd.read_csv("encoded.csv", header=0, names=['rsID', 'sequence'])
encoded.head()

rsID                                           sequence
0  rs577013928   ttttttttttttttttttttttttttttttttttttttttttttt...
1  rs565082899   ttttttttttttttttttttttttttttttttttttttttttttt...
2  rs540382744   ttttttttttttttttttttttttttttttttttttttttttttt...
3  rs573244332   ttttttttttttttttttttttttttttttttttttttttttttt...
4  rs539162497   ttttttttttttttttttttttttttttttttttttttttttttt...

In [15]:
encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1053845 entries, 0 to 1053844
Data columns (total 2 columns):
 #   Column    Non-Null Count    Dtype 
---  ------    --------------    ----- 
 0   rsID      1053845 non-null  object
 1   sequence  1053845 non-null  object
dtypes: object(2)
memory usage: 16.1+ MB


In [16]:
encoded['sequence'].iloc[0:3]

0     ttttttttttttttttttttttttttttttttttttttttttttt...
1     ttttttttttttttttttttttttttttttttttttttttttttt...
2     ttttttttttttttttttttttttttttttttttttttttttttt...
Name: sequence, dtype: object

In [17]:
def makeArray(strings):
    
    # initialize sample array with empty list
    bebG, cheG, esnG, gbrG, pelG = [], [], [], [], []
    bebH, cheH, esnH, gbrH, pelH = [], [], [], [], []
    
    # swap the keys and values in the dictionary below
    nested_dictionary = {'GBR':{'e':'a', 'f':'b', 'g':'c', 'h': 'd'},
                         'PEL':{'i':'a', 'j':'b', 'k':'c', 'l': 'd'},
                         'ESN':{'m':'a', 'n':'b', 'o':'c', 'p': 'd'},
                         'BEB':{'q':'a', 'r':'b', 's':'c', 't': 'd'},
                         'CHE':{'u':'a', 'v':'b', 'w':'c', 'x': 'd'}}

    ginfo = {'a':'1|0', 'b':'1|1', 'c':'0|1', 'd':'0|0'}

    dic = {'e':'GBR', 'f':'GBR', 'g':'GBR', 'h':'GBR',
           'i':'PEL', 'j':'PEL', 'k':'PEL', 'l':'PEL',
           'm':'ESN', 'n':'ESN', 'o':'ESN', 'p':'ESN',
           'q':'BEB', 'r':'BEB', 's':'BEB', 't':'BEB',
           'u':'CHE', 'v':'CHE', 'w':'CHE', 'x':'CHE'}

    for string in strings:
        string = string.strip()
        genotypes = {}
        N = len(string)
        # initialize haplotype dictionary with 462 zeros for each sample
        haplotypes = {'BEB':[0]*N, 'CHE':[0]*N, 'ESN':[0]*N, 'GBR':[0]*N, 'PEL':[0]*N}

        for i, c in enumerate(string):
            # take sample as key and 0|1 etc as value
            genotypes.setdefault(dic[c], []).append(ginfo[nested_dictionary[dic[c]][c]])
            # set 1 in which position sample present
            haplotypes[dic[c]][i] = 1

        # sort dictionary alphabetically
        genotypes = dict(sorted(genotypes.items(), key = lambda x:x[0].lower()))
        # split each 0|1 etc by | and make a list,,,thus apply on each sample
        genotype_array = [[list(map(int, v.split('|'))) for v in val] for val in genotypes.values()]
        # create haplotype array
        haplotype_array = [val for val in haplotypes.values()]

        # extracting genotype array samples
        bebG.append(genotype_array[0])
        cheG.append(genotype_array[1])
        esnG.append(genotype_array[2])
        gbrG.append(genotype_array[3])
        pelG.append(genotype_array[4])
        
        # extracting haplotype array samples
        bebH.append(haplotype_array[0])
        cheH.append(haplotype_array[1])
        esnH.append(haplotype_array[2])
        gbrH.append(haplotype_array[3])
        pelH.append(haplotype_array[4])
        
    return (bebG, cheG, esnG, gbrG, pelG), (bebH, cheH, esnH, gbrH, pelH)

In [48]:
# passing first 3 sequences into makeArray function
g, h = makeArray(encoded['sequence'].iloc[10:17]) # we can pass a list inside the function as [snp1, snp2, snp3, ...]

# extract genotype array into samples
bebG, cheG, esnG, gbrG, pelG = g

# extract haplotype array into samples
bebH, cheH, esnH, gbrH, pelH = h

print(gbrG)

[[[1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [1, 1], [0, 0], [0, 0], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 1], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 

In [63]:
print(esnG)

[[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]], [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 

In [64]:
new_fused_array = np.array([x+y for x,y in zip(gbrG,esnG)])

In [65]:
new_fused_array

array([[[1, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [1, 1],
        ...,
        [1, 0],
        [1, 0],
        [0, 0]],

       ...,

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]]])

In [51]:
np.array(gbrG).shape

(7, 91, 2)

In [49]:
import allel
g = allel.GenotypeArray(gbrG)
ac = g.count_alleles()
allel.tajima_d(ac)

-0.4723651726053071

In [53]:
allel.haplotype_diversity(gbrH)

0.3159957548223728

In [ ]:
allel.patterson_fst()

In [70]:
new = allel.GenotypeArray(new_fused_array)

In [72]:
new

<GenotypeArray shape=(7, 190, 2) dtype=int64>
1/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
0/0 0/0 1/1 0/0 0/0 ... 0/0 0/0 1/0 1/0 0/0
...
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0

In [77]:
subpops = [[0, 1, 2 , 3 , 4 , 5 , 6, 7],[0, 1, 2 , 3 , 4 , 5 ,6, 7]]


In [ ]:
subpops = [[]]

In [74]:
g = np.array(new_fused_array)

In [78]:
>>> ac1 = new.count_alleles(subpop=subpops[0])
>>> ac2 = new.count_alleles(subpop=subpops[1])

In [82]:
num, den = allel.hudson_fst(ac1, ac2)

In [90]:
den

array([0.1171875, 0.       , 0.3046875, 0.3046875, 0.       , 0.       ,
       0.       ])

In [84]:
num

array([-0.0078125,  0.       , -0.0203125, -0.0203125,  0.       ,
        0.       ,  0.       ])

In [83]:
allel.hudson_fst(ac1, ac2)

(array([-0.0078125,  0.       , -0.0203125, -0.0203125,  0.       ,
         0.       ,  0.       ]),
 array([0.1171875, 0.       , 0.3046875, 0.3046875, 0.       , 0.       ,
        0.       ]))

In [92]:
# fst = num / den

In [80]:
allel.weir_cockerham_fst(new, subpops)

(array([[-0.00390625, -0.00390625],
        [ 0.        ,  0.        ],
        [-0.01729911, -0.01729911],
        [-0.01729911, -0.01729911],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ]]),
 array([[0.        , 0.        ],
        [0.        , 0.        ],
        [0.10714286, 0.10714286],
        [0.10714286, 0.10714286],
        [0.        , 0.        ],
        [0.        , 0.        ],
        [0.        , 0.        ]]),
 array([[0.0625, 0.0625],
        [0.    , 0.    ],
        [0.0625, 0.0625],
        [0.0625, 0.0625],
        [0.    , 0.    ],
        [0.    , 0.    ],
        [0.    , 0.    ]]))

In [50]:
ac

<AlleleCountsArray shape=(7, 2) dtype=int32>
170  12
181   1
163  19
...
182   0
182   0
182   0

In [21]:
'''# to iterate over whole variants
for i in range(0, encoded.shape[0], 3):
    makeArray(encoded['sequence'].iloc[i:i+3])'''

"# to iterate over whole variants\nfor i in range(0, encoded.shape[0], 3):\n    makeArray(encoded['sequence'].iloc[i:i+3])"